#  _____                                   _____           _ _           _
# |  __ \                                 |_   _|         | (_)         | |
# | |  | | __ _ _ __ ___   __ _  __ _  ___  | |  _ __   __| |_  ___ __ _| |_ ___  _ __
# | |  | |/ _` | '_ ` _ \ / _` |/ _` |/ _ \ | | | '_ \ / _` | |/ __/ _` | __/ _ \| '__|
# | |__| | (_| | | | | | | (_| | (_| |  __/_| |_| | | | (_| | | (_| (_| | || (_) | |
# |_____/ \__,_|_| |_| |_|\__,_|\__, |\___|_____|_| |_|\__,_|_|\___\__,_|\__\___/|_|
#  ____                       _  __/ |       _            __ ___
# |  _ \            /\       | ||___/       | |          /_ |__ \
# | |_) |_   _     /  \   ___| |__   ___  __| | ___  _ __ | |  ) |
# |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#         __/ |
#        |___/

# Plugin Version | do not touch this
version: v1.0
